version: "3.9"

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: DeminMS-my-netology-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    networks:
      - DeminMS-my-netology-hw

  pushgateway:
    image: prom/pushgateway:latest
    container_name: DeminMS-my-netology-pushgateway
    restart: unless-stopped
    ports:
      - "9091:9091"
    networks:
      - DeminMS-my-netology-hw

volumes:
  prometheus-data:

networks:
  DeminMS-my-netology-hw:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
